### PR TITLE
fix: enable downloading holder list

### PR DESCRIPTION
**Pull request by Keith-CY**
1. recover the download button of holder list
2. fix download url

### CODE REVIEW

**Comment by Keith-CY** [comment]
Preview: https://godwoken-explorer-ui-git-fix-download-holder-list-nervosnet.vercel.app/token/6841

**Review by yanguoyu — APPROVED** [review]

**Comment by FrederLu** [comment]
image
@zmcNotafraid   The Transaction Count in the downloaded holder table needs to display the data of Txns, and it is empty now.

**Comment by zmcNotafraid** [comment]
> image
> 
> @zmcNotafraid The Transaction Count in the downloaded holder table needs to display the data of Txns, it is empty now.

Transaction count has fixed.Please check agagin @FrederLu

**Comment by FrederLu** [comment]
> > image
> > @zmcNotafraid The Transaction Count in the downloaded holder table needs to display the data of Txns, it is empty now.
> 
> Transaction count has fixed.Please check agagin @FrederLu

image

@zmcNotafraid @Keith-CY 
**The data verification of GodwokenToken on testnet_v1 hloders passed.**

**But** found a problem with the hloders data of pCKB. 
image
image
1. The data is messy.
2. The overall number is not right.
----------------------------------------------------------------------------------------------------------------------------
image

3. The Bridged Transfers data sequence of pCKB is normal, but only 5,000 pieces of data are exported like the holders data, and not all of them are exported.

**Comment by Keith-CY** [comment]
> > > image
> > > @zmcNotafraid The Transaction Count in the downloaded holder table needs to display the data of Txns, it is empty now.
> > 
> > 
> > Transaction count has fixed.Please check agagin @FrederLu
> 
> image
> 
> @zmcNotafraid @Keith-CY **The data verification of GodwokenToken on testnet_v1 hloders passed.**
> 
> **But** found a problem with the hloders data of pCKB. image image
> 
> 1. The data is messy.
> 2. The overall number is not right.
> 
> image
> 
> 3. The Bridged Transfers data sequence of pCKB is normal, but only 5,000 pieces of data are exported like the holders data, and not all of them are exported.

For the last point(up to 5000 records are exported), it's by design. We limit the maximum of data to export for performance, users who need more info could contact us directly.

The `up to 5000` is prompted on the download button
image

**Comment by FrederLu** [comment]
> Found a problem with the hloders data of pCKB. 
>image
> 
@zmcNotafraid The export data is confusing and needs to be looked at.

**Comment by zmcNotafraid** [comment]
> > Found a problem with the hloders data of pCKB.
> > image
> 
> @zmcNotafraid The export data is confusing and needs to be looked at.

@FrederLu  The data's sort have bugs.Now it's fixed.You can check again

**Comment by FrederLu** [comment]
Now the interface download file is normal, but there are some problems with the consistency of the exported file and page data. It is confirmed that the data inconsistency involves the data on the ckb, which is not easy to handle for the time being. We will pay more attention to it later.

**Review by FrederLu — APPROVED** [review]

**Pull request merged**
