### PR TITLE
feat: update-ui, block list

### PR DESCRIPTION
**Pull request by qiweiii**
ui for block list page: `/blocks`

### CODE REVIEW

**Comment by Kirl70** [comment]
image
箭头部分缺少线条，红框部分线条色值需改为#F0F0F0 @qiweiii

**Comment by FrederLu** [comment]
image

image

@qiweiii 
`Blocks from #189668 to #189682`  the first letters of From and To need to be capitalized.

@Kirl70 
1、`Showing The Last 500k Records`  is a prompt message or can you jump after clicking?
2、If the number of pagination is large, it seems inconvenient to quickly preview the first and last pages during the tour.

**Comment by Kirl70** [comment]
> image
> 
> image
> 
> @qiweiii `Blocks from #189668 to #189682` the first letters of From and To need to be capitalized.
> 
> @Kirl70 1、`Showing The Last 500k Records` is a prompt message or can you jump after clicking? 2、If the number of pagination is large, it seems inconvenient to quickly preview the first and last pages during the tour.


1、Showing The Last 500k Records  It is a prompt message. 

2、Regarding page jumps, there are technical limitations to the implementation. For details, please refer to the instructions here on the design draft.
image

**Comment by FrederLu** [comment]
image
image
The spacing between 3 places on the blcok page of the android mobile phone is too large.

**Comment by qiweiii** [comment]
> image
> 
> image
> 
> @qiweiii 
> 
> The spacing between 3 places on the blcok page of the android mobile phone is too large.
> 
> 

1. For table I think the current spacing is OK since different devices have different screen width

2. For paginations, I am not sure if I need to change these, since mobile devices and tablets all have different screen sizes... So the current implementation is that if the screen width is under certain value (maybe 600), the paginations will be left aligned.

@Kirl70 Do I need to fix these?

**Comment by Kirl70** [comment]
> > image
> > image
> > @qiweiii
> > The spacing between 3 places on the blcok page of the android mobile phone is too large.
> 
> 1. For table I think the current spacing is OK since different devices have different screen width
> 2. For paginations, I am not sure if I need to change these, since mobile devices and tablets all have different screen sizes... So the current implementation is that if the screen width is under certain value (maybe 600), the paginations will be left aligned.
> 
> @Kirl70 Do I need to fix these?

I think these two problems are normal, because the mobile terminal needs to adjust a lot of sizes, so here we only need to ensure that the left side is aligned and an adaptive space is left on the right side. The design draft is the best presentation effect, but it is technically difficult to achieve the best effect in different sizes.


Or we can align the pagination and header information in the center, so that their positions are the same on different devices, do you think it needs to be centered? @FrederLu @qiweiii 

image

**Comment by FrederLu** [comment]
@Kirl70 @qiweiii 
If we only need to align the left side and leave an adaptive space on the right side, I think it's ok now. I used to look at the UI and felt that the spacing was a bit too large.

**Comment by qiweiii** [comment]
I feel align left is okay, align center on medium size screen like 900-100 feels a bit weired (personally)

**Comment by Kirl70** [comment]
Ok, then make it left-aligned, and the space on the right is adaptive.

**Comment by qiweiii** [comment]
@FrederLu Please check if the problems are fixed, thanks

**Review by FrederLu — APPROVED** [review]

**Review by Keith-CY — APPROVED** [review]

**Pull request merged**
