### PR TITLE
feat: refine tx info page

### PR DESCRIPTION
**Pull request by Keith-CY**
This PR refines title, download, overview and basic info of
the tx info page

erc20 transfer list will be refined later because pagination
could be reused when another PR(tx list) is merged

raw data will be designed later because it's introduced after
the design is confirmed

### CODE REVIEW

**Comment by FrederLu** [comment]
image

https://godwoken-explorer-asg1zilii-nervosnet.vercel.app/zh-CN/tx/0xba93589cfb21dd40b597a8e75afe77af615735aabfbac8119f57bfbe9b24d07d

There is one less icon in this data. Is it caused by a problem with this data?

**Comment by FrederLu** [comment]
image
image

The last column of data in the tab list needs to be right-aligned.

**Review by qiweiii — APPROVED** [review]

**Comment by FrederLu** [comment]
image
image

The first letter of Transaction info needs to be capitalized.

**Comment by Keith-CY** [comment]
> image
> 
> image
> 
> The first letter of Transaction info needs to be capitalized.

Fixed by [c2dcc14](https://github.com/Magickbase/godwoken-explorer-ui/pull/344/commits/c2dcc14e4874add58ccb12466fbc323912172321)

**Comment by FrederLu** [comment]
image
image

Compared with the UI draft Transaction Info page block info, there is an icon to the right of the L1 Block number.

**Comment by FrederLu** [comment]
image
image

1、Compared with the ERC20 Transfers tab of the UI draft Transaction Info page on the 27th, there is no token column information, and the ckUSDT token icon is displayed abnormally. 

2、Pagination information does not display current information.

**Comment by FrederLu** [comment]
image
image

Display on Android phone:
1、Interact With Contract message display is blocked.
2、The style of Input does not match the UI draft.

**Comment by Keith-CY** [comment]
> image
> 
> image
> 
> Compared with the UI draft Transaction Info page block info, there is an icon to the right of the L1 Block number.

This follows the rule that every link that opens an external tab/window should have a `open in new` icon, prior to UI design.

**Comment by Keith-CY** [comment]
> image
> 
> image
> 
> 1、Compared with the ERC20 Transfers tab of the UI draft Transaction Info page on the 27th, there is no token column information, and the ckUSDT token icon is displayed abnormally.
> 
> 2、Pagination information does not display current information.

For the first point, a `token` column` was added accidentally because it was introduced in the new design, I'll hide it in this PR

For the second point, we are using cursor-based pagination(https://github.com/Magickbase/godwoken_explorer/discussions/201#discussioncomment-2690762) so explicitly specified pages are not supported for now(due to a technical reason), only `prev page` and `next page` are supported, we aim to support `< 1, 2, 3, 4, 5 >` but now only `< >` can be implemented.

With the adoption of new graphql API, all lists (except the block list) will use this pagination.

**Comment by Keith-CY** [comment]
> image
> 
> image
> 
> 1、Compared with the ERC20 Transfers tab of the UI draft Transaction Info page on the 27th, there is no token column information, and the ckUSDT token icon is displayed abnormally.
> 
> 2、Pagination information does not display current information.

`Token` column is hidden by [5082e43](https://github.com/Magickbase/godwoken-explorer-ui/pull/344/commits/5082e43c1fb932f4ab73ceb83fe8caec693a628f)

**Comment by Keith-CY** [comment]
> image
> 
> image
> 
> Display on Android phone: 1、Interact With Contract message display is blocked. 2、The style of Input does not match the UI draft.

Wrap of `interact with contract` is fixed by [6cb8b63](https://github.com/Magickbase/godwoken-explorer-ui/pull/344/commits/6cb8b63ad01289f2373bdf7dba2a6588d8e8eba6)

**Comment by FrederLu** [comment]
image


Open the [url](https://godwoken-explorer-rkizlgp33-nervosnet.vercel.app/zh-CN/tx/0xcbca380e8f4085883cec1457afc57225dc68f3476abaa8c314ff69644595a71c?search=0xcbca380e8f4085883cec1457afc57225dc68f3476abaa8c314ff69644595a71c) in WeChat on the android mobile phone, click the check hotspot, the selected yellow box will be displayed, and you need to click the blank space to hide it.The chrome browser on the mobile phone displays fine.

**Comment by Keith-CY** [comment]
> image
> 
> Open the [url](https://godwoken-explorer-rkizlgp33-nervosnet.vercel.app/zh-CN/tx/0xcbca380e8f4085883cec1457afc57225dc68f3476abaa8c314ff69644595a71c?search=0xcbca380e8f4085883cec1457afc57225dc68f3476abaa8c314ff69644595a71c) in WeChat on the android mobile phone, click the check hotspot, the selected yellow box will be displayed, and you need to click the blank space to hide it.The chrome browser on the mobile phone displays fine.

It is fine, the highlight is one of `accessibility` attribute that tell user it's interactive.

**Review by FrederLu — APPROVED** [review]

**Pull request merged**
