### PR TITLE
feat: enable video autoplay in wechat

### PR DESCRIPTION
**Pull request by Keith-CY**
This PR fixed the issue that the video in banner doesn't play automatically when page is opened in wechat webview.

However, I notice that the video flashes on switching language(visiting a new page), it could be another issue and would be handled by another PR.

### CODE REVIEW

**Comment by Keith-CY** [comment]
This PR introduces a poster for the video playing in the banner, I just take a screenshot of the video now but find the screenshot has almost the same size(200k) of the video, which makes the screenshot not so effective. Could you provide posters of smaller size @Kirl70 

image

**Review by qiweiii — APPROVED** [review]

**Comment by FrederLu** [comment]
image

When I open it in WeChat, I can now see the picture (the picture was blank before), but only static pictures are displayed without dynamic effects.

**Comment by Cedar67** [comment]
> image
> 
> @Keith-CY When I open it in WeChat, I can now see the picture (the picture was blank before), but only static pictures are displayed without dynamic effects.

FYI  @Keith-CY 
This problem may be due to the difference in wechat client. My ios wechat can display flash normally. According to Freder's feedback, flash can not be displayed on his Android wechat.

**Comment by Keith-CY** [comment]
> image
> 
> @Keith-CY When I open it in WeChat, I can now see the picture (the picture was blank before), but only static pictures are displayed without dynamic effects.

I see part of a white box outside the screenshot, is there a dark modal under the banner and block list but over the `latest blocks` text?

**Comment by FrederLu** [comment]
> > image
> > @Keith-CY When I open it in WeChat, I can now see the picture (the picture was blank before), but only static pictures are displayed without dynamic effects.
> 
> I see part of a white box outside the screenshot, is there a dark modal under the banner and block list but over the `latest blocks` text?

image
@Keith-CY 
This is the dark tone of my mobile phone system, and the white tone is shown in the screenshot.

**Comment by Keith-CY** [comment]
> > > image
> > > @Keith-CY When I open it in WeChat, I can now see the picture (the picture was blank before), but only static pictures are displayed without dynamic effects.
> > 
> > 
> > I see part of a white box outside the screenshot, is there a dark modal under the banner and block list but over the `latest blocks` text?
> 
> image
> 
> @Keith-CY This is the dark tone of my mobile phone system, and the white tone is shown in the screenshot.

Is the video missing, or just lazily loaded when system is set to white tone

**Pull request merged**
