### PR TITLE
feat: enable erc 1155

### PR DESCRIPTION
**Pull request by Keith-CY**
This PR enables functions of ERC 1155
1. add a nav button in `Token` menu
image
2. ERC 1155 Token Collection List: https://godwoken-explorer-ui-git-enable-erc-1155-magickbase.vercel.app/multi-token-collections
3. ERC 1155 Token Collection Info: https://godwoken-explorer-ui-git-enable-erc-1155-magickbase.vercel.app/multi-token-collection/0xeeb92d6b3999abdc8cc0226069d88c07f241fd4c
4. ERC 1155 Token Item Info: https://godwoken-explorer-ui-git-enable-erc-1155-magickbase.vercel.app/multi-token-item/0xeeb92d6b3999abdc8cc0226069d88c07f241fd4c/4
5. ERC 1155 Asset List of an account: https://godwoken-explorer-ui-git-enable-erc-1155-magickbase.vercel.app/account/0xc4e2fe8694b5b15816727e54b5cad9f622e9c6bc?tab=erc-1155-assets

Ref: https://github.com/Magickbase/godwoken_explorer/issues/854

### CODE REVIEW

**Review by qiweiii — APPROVED** [review]

**Comment by FrederLu** [comment]
@Keith-CY 
The data in the ERC 1155 Token Collection Info stats is displayed like this. Is there less Item Count?
https://godwoken-explorer-6z22m4y4m-magickbase.vercel.app/multi-token-collection/0xdcbd950f8246cd1e2f4da41cd91219abeb823935?tab=inventory

image

**Comment by FrederLu** [comment]
image
image
@Keith-CY @Kirl70 K
Confirm a place that is different from the ui draft.

**Comment by Kirl70** [comment]
> image
> 
> image
> 
> @Keith-CY @Kirl70
> Confirm a place that is different from the ui draft.

In the PRD https://github.com/Magickbase/godwoken_explorer/issues/854#issuecomment-1220169844
only the address of the holder is shown here, maybe the demand has changed

**Comment by Keith-CY** [comment]
There're two inventory lists
1. inventory of an erc 1155 collection
The element of erc 1155 collection inventory is a `token type` which is a batch of token items, and they may belong to various users. So the `token id` and `quantity` is shown.

2. inventory of an erc 1155 token type
The element of erc 1155 token type inventory is a `token item`, they belong to the same `token id` and is held by a specific user. So `owner address` is shown.

**Comment by Keith-CY** [comment]
Seems that `owner address` is missing in the `inventory` API, is there another API to fetch the item list of a specific token type? @Naupio

**Comment by Naupio** [comment]
> 

does this api up to specification?

```graphql
    query {
      erc1155_user_inventory(
        input: {
          contract_address: "0xe6903e124e5bdae8784674eb625f1c212efc789e"
          token_id: 0
        }
      ) {
        entries {
          token_id
          address_hash
          token_contract_address_hash
          value
          udt {
            id
            name
            eth_type
          }
        }
        metadata {
          total_count
          after
          before
        }
      }
    }
```
result:
```json
{
  "data": {
    "erc1155_user_inventory": {
      "entries": [
        {
          "address_hash": "0xc6e58fb4affb6ab8a392b7cc23cd3fef74517f6c",
          "token_contract_address_hash": "0xe6903e124e5bdae8784674eb625f1c212efc789e",
          "token_id": "0",
          "udt": {
            "eth_type": "ERC1155",
            "id": 48472,
            "name": null
          },
          "value": "73"
        },
        {
          "address_hash": "0x77680eee2294fcd438ddc4ffbb566c20a150ab90",
          "token_contract_address_hash": "0xe6903e124e5bdae8784674eb625f1c212efc789e",
          "token_id": "0",
          "udt": {
            "eth_type": "ERC1155",
            "id": 48472,
            "name": null
          },
          "value": "1"
        },
        {
          "address_hash": "0x91368accd2b7c9807cd9dc889158e5294f4105f0",
          "token_contract_address_hash": "0xe6903e124e5bdae8784674eb625f1c212efc789e",
          "token_id": "0",
          "udt": {
            "eth_type": "ERC1155",
            "id": 48472,
            "name": null
          },
          "value": "18"
        },
        {
          "address_hash": "0x46b6f87debd8f7607d00df47c31d2dc6d9999999",
          "token_contract_address_hash": "0xe6903e124e5bdae8784674eb625f1c212efc789e",
          "token_id": "0",
          "udt": {
            "eth_type": "ERC1155",
            "id": 48472,
            "name": null
          },
          "value": "11001"
        }
      ],
      "metadata": {
        "after": null,
        "before": null,
        "total_count": 4
      }
    }
  }
}
```

**Comment by Keith-CY** [comment]
> > 
> 
> does this api meet demand?
> 
> ```graphql
>     query {
>       erc1155_user_inventory(
>         input: {
>           contract_address: "0xe6903e124e5bdae8784674eb625f1c212efc789e"
>           token_id: 0
>         }
>       ) {
>         entries {
>           token_id
>           address_hash
>           token_contract_address_hash
>           value
>           udt {
>             id
>             name
>             eth_type
>           }
>         }
>         metadata {
>           total_count
>           after
>           before
>         }
>       }
>     }
> ```
> 
> result:
> 
> ```json
> {
>   "data": {
>     "erc1155_user_inventory": {
>       "entries": [
>         {
>           "address_hash": "0xc6e58fb4affb6ab8a392b7cc23cd3fef74517f6c",
>           "token_contract_address_hash": "0xe6903e124e5bdae8784674eb625f1c212efc789e",
>           "token_id": "0",
>           "udt": {
>             "eth_type": "ERC1155",
>             "id": 48472,
>             "name": null
>           },
>           "value": "73"
>         },
>         {
>           "address_hash": "0x77680eee2294fcd438ddc4ffbb566c20a150ab90",
>           "token_contract_address_hash": "0xe6903e124e5bdae8784674eb625f1c212efc789e",
>           "token_id": "0",
>           "udt": {
>             "eth_type": "ERC1155",
>             "id": 48472,
>             "name": null
>           },
>           "value": "1"
>         },
>         {
>           "address_hash": "0x91368accd2b7c9807cd9dc889158e5294f4105f0",
>           "token_contract_address_hash": "0xe6903e124e5bdae8784674eb625f1c212efc789e",
>           "token_id": "0",
>           "udt": {
>             "eth_type": "ERC1155",
>             "id": 48472,
>             "name": null
>           },
>           "value": "18"
>         },
>         {
>           "address_hash": "0x46b6f87debd8f7607d00df47c31d2dc6d9999999",
>           "token_contract_address_hash": "0xe6903e124e5bdae8784674eb625f1c212efc789e",
>           "token_id": "0",
>           "udt": {
>             "eth_type": "ERC1155",
>             "id": 48472,
>             "name": null
>           },
>           "value": "11001"
>         }
>       ],
>       "metadata": {
>         "after": null,
>         "before": null,
>         "total_count": 4
>       }
>     }
>   }
> }
> ```

LGTM

**Comment by Keith-CY** [comment]
After implementation, I found an awkward issue 😓

For a specific token type in an erc 1155 collection, say, token `Nervape#1`(collection name is Nervape and type id is 1`, it consist of 1000 token items

Then the inventory of `type id 1` would be

<table>
<tr>
	<td> Nervape#1 Cover
	<td> Nervape#1 Cover
	<td> Nervape#1 Cover
	<td> Nervape#1 Cover
	<td> Nervape#1 Cover
<tr>
	<td> owner 1
	<td> owner 2
	<td> owner 3
	<td> owner 4
	<td> owner 5
</table>

It's exactly the same as the `holder list`(and holder list shows quantity of token type owned by an address)
image

Maybe we can only keep the holder list for a specific `erc 721 token type` 🙈 any idea from @FrederLu @Kirl70 @Naupio

**Comment by Kirl70** [comment]
> After implementation, I found an awkward issue 😓
> 
> For a specific token type in an erc 1155 collection, say, token `Nervape#1`(collection name is Nervape and token type id is 1), it consist of 1000 token items
> 
> Then the inventory of `type id 1` would be
> 
> Nervape#1 Cover	Nervape#1 Cover	Nervape#1 Cover	Nervape#1 Cover	Nervape#1 Cover
> owner 1	owner 2	owner 3	owner 4	owner 5
> It's exactly the same as the `holder list`(and holder list shows quantity of token type owned by an address) image
> 
> Maybe we can only keep the holder list for a specific `erc 721 token type` 🙈 any idea from @FrederLu @Kirl70 @Naupio

If the inventory address is the same as the address on the holder list and each cover is the same as the main cover of the collection then it is indeed a duplicate function page, so I think the inventory page should be able to be deleted?

image

**Comment by FrederLu** [comment]
From the concept of `directory` and `holder`, pages need to be separated. However, considering the particularity of data display, two dimensions of data must be displayed on both pages, just a different form of presentation.

> After implementation, I found an awkward issue 😓
> 
> For a specific token type in an erc 1155 collection, say, token `Nervape#1`(collection name is Nervape and token type id is 1), it consist of 1000 token items
> 
> Then the inventory of `type id 1` would be
> 
> Nervape#1 Cover	Nervape#1 Cover	Nervape#1 Cover	Nervape#1 Cover	Nervape#1 Cover
> owner 1	owner 2	owner 3	owner 4	owner 5
> It's exactly the same as the `holder list`(and holder list shows quantity of token type owned by an address) image
> 
> Maybe we can only keep the holder list for a specific `erc 721 token type` 🙈 any idea from @FrederLu @Kirl70 @Naupio

**Comment by Keith-CY** [comment]
Yes, the both list share the same data and deliver almost the same information, so in the aspect of data, they are duplicated and only one is necessary @Kirl70.

But after reading @FrederLu's comment I also think it's reasonable to keep them all because the same data could be viewed from various dimensions, one from biggest holders, and the other from token items themselves.

I'll keep them all but add the missing `field` quantity in the `inventory list`(`quantity` shows in the holder list)

**Comment by Keith-CY** [comment]
I've updated the inventory of erc 1155 token type, please have a review @FrederLu 
https://godwoken-explorer-ui-git-enable-erc-1155-magickbase.vercel.app/multi-token-item/0xeeb92d6b3999abdc8cc0226069d88c07f241fd4c/4?tab=inventory

**Comment by FrederLu** [comment]
https://godwoken-explorer-os6sxho0q-magickbase.vercel.app/zh-CN/multi-token-collection/0xa5ceef41b9df859194c593b90d4c51a8f5a8a551?tab=inventory

https://godwoken-explorer-os6sxho0q-magickbase.vercel.app/multi-token-item/0xa5ceef41b9df859194c593b90d4c51a8f5a8a551/2?tab=inventory

When clicking on the Inventory tab, the NFT image appears to be constantly refreshed and enlarged.

**Comment by Keith-CY** [comment]
> [godwoken-explorer-os6sxho0q-magickbase.vercel.app/zh-CN/multi-token-collection/0xa5ceef41b9df859194c593b90d4c51a8f5a8a551?tab=inventory](https://godwoken-explorer-os6sxho0q-magickbase.vercel.app/zh-CN/multi-token-collection/0xa5ceef41b9df859194c593b90d4c51a8f5a8a551?tab=inventory)
> 
> [godwoken-explorer-os6sxho0q-magickbase.vercel.app/multi-token-item/0xa5ceef41b9df859194c593b90d4c51a8f5a8a551/2?tab=inventory](https://godwoken-explorer-os6sxho0q-magickbase.vercel.app/multi-token-item/0xa5ceef41b9df859194c593b90d4c51a8f5a8a551/2?tab=inventory)
> 
> When clicking on the Inventory tab, the NFT image appears to be constantly refreshed and enlarged.

It's been fixed by [7837d19](https://github.com/Magickbase/godwoken-explorer-ui/pull/648/commits/7837d1900ae898a5e61ec43e20734b227d1a16a5)

Preview: https://godwoken-explorer-bd1gk0cbr-magickbase.vercel.app/multi-token-collection/0xa5ceef41b9df859194c593b90d4c51a8f5a8a551?tab=inventory

**Comment by FrederLu** [comment]
https://godwoken-explorer-bd1gk0cbr-magickbase.vercel.app/multi-token-item/0x2c130958af59e61f5d8a404c59494586b65f4957/3
image
The token amount should be 1 each, now each is 3, and there is an additional column of data behind.

**Comment by Keith-CY** [comment]
> [godwoken-explorer-bd1gk0cbr-magickbase.vercel.app/multi-token-item/0x2c130958af59e61f5d8a404c59494586b65f4957/3](https://godwoken-explorer-bd1gk0cbr-magickbase.vercel.app/multi-token-item/0x2c130958af59e61f5d8a404c59494586b65f4957/3) image
> 
> @Keith-CY The token amount should be 1 each, now each is 3, and there is an additional column of data behind.

Should be fixed by [a66aeaa](https://github.com/Magickbase/godwoken-explorer-ui/pull/648/commits/a66aeaa06d5e73158917289cfe7b0d78dcfa6f86)

The list component is reused on token collection page and token type/id page.

When it's on token collection page, the list has a `token id` column, while when it's on token type page/id page, the list should hide the `token id` column.

The error here is that `table header of token id` is removed but `table cell` is not. After fix, list on token collection page should be like
image
and list on token type/id page should be like
image

**Review by FrederLu — APPROVED** [review]

**Pull request merged**
