### PR TITLE
feat: optimize style of tooltip

### PR DESCRIPTION
**Pull request by Keith-CY**
1. make text unwrapped if it consists of several words
2. align tooltip to right border for mobile layout

Ref: https://github.com/Magickbase/godwoken_explorer/issues/1199

---
1. Homepage: https://godwoken-explorer-ui-git-short-tooltip-unwrapped-magickbase.vercel.app/
Before
image
After
image
image

2. Account page: https://godwoken-explorer-ui-git-short-tooltip-unwrapped-magickbase.vercel.app/account/0xbe65f55eab96cc2a64e7b509421900b62c15e0c6
Before
image
image
After
image
image
image
image

3. Token page: https://godwoken-explorer-ui-git-short-tooltip-unwrapped-magickbase.vercel.app/token/375
Before
image
After
image

### CODE REVIEW

**Comment by FrederLu** [comment]
1、Missing `Submitted` on mobile.
image
image

2、When the downloaded tooltip is displayed in Chinese, the distance between left and right is larger than that in English.
image
image

**Review by qiweiii — APPROVED** [review]

**Comment by Keith-CY** [comment]
> 1、Missing `Submitted` on mobile. image image
> 
> 2、When the downloaded tooltip is displayed in Chinese, the distance between left and right is larger than that in English. image image

`Information has been submitted` was truncated by `max-width: 150px` at https://github.com/Magickbase/godwoken-explorer-ui/blob/develop/styles/tooltip.scss#L35
Why is the max width set to 150px @JeffreyMa597

**Review by JeffreyMa597 — APPROVED** [review]

**Comment by JeffreyMa597** [comment]
> Why is the max width set to 150px @JeffreyMa597

@Keith-CY  This is supposed to solve the problem of the right side of the floating layer being clipped by the page border when centered. Right alignment was not considered at the time.

**Comment by Keith-CY** [comment]
> > Why is the max width set to 150px @JeffreyMa597
> 
> @Keith-CY This is supposed to solve the problem of the right side of the floating layer being clipped by the page border when centered. Right alignment was not considered at the time.

Got it

**Comment by Keith-CY** [comment]
> 1、Missing `Submitted` on mobile. image image
> 
> 2、When the downloaded tooltip is displayed in Chinese, the distance between left and right is larger than that in English. image image

These errors have been fixed

image
image

**Review by FrederLu — APPROVED** [review]

**Pull request merged**
