### PR TITLE
Fix: Truncated field misses ellipsis and label is wrapped

### PR DESCRIPTION
**Pull request by JeffreyMa597**
What problem does this PR solve?
------

There are two points in this issue:
1、Deployer and Deploy Transaction fields are truncated without ellipsis
2、Deploy Transaction label is wrapped

Ref: https://github.com/Magickbase/godwoken_explorer/issues/1150

Check List
------

### Test
e2e Test
### Task
none

### CODE REVIEW

**Review by Keith-CY — APPROVED** [review]

**Comment by FrederLu** [comment]
@JeffreyMa597 
image
Now the style is working fine, but there are 2 small problems:
1. The information of `Deploy Transaction` should be left-aligned like the top and bottom;
2. The ellipsis must have the same color system as the text (there are 2 color systems for testnet and online);

**Comment by JeffreyMa597** [comment]
@Keith-CY I found the label of `Basic Info` which named `Deploy transaction` will be wrapped when I set the width as the design in the mobile style. Should I change this width to avoid line wrapping? This may not match the design width.
image

image

**Comment by Keith-CY** [comment]
> @Keith-CY In the mobile style, I found the label of `Basic Info` which is named `Deploy transaction` will be wrapped when I set the width as the design. Should I change this width to avoid line wrapping? This may not match the design width. image
> 
> image

The label is supposed to be not wrapped and the width in mobile layout could be slight changed for the real data

**Comment by FrederLu** [comment]
image

The ellipsis and text color after `Deployer` are inconsistent.

**Review by FrederLu — APPROVED** [review]

**Pull request merged**
