### PR TITLE
fix: mui alert component default severity

### PR DESCRIPTION
**Pull request by qiweiii**
fixes: https://github.com/Magickbase/godwoken_explorer/issues/909

https://user-images.githubusercontent.com/32790369/190860092-98d257d5-5ae6-4ea2-bcfe-585d8e3f8241.mov

### CODE REVIEW

**Review by Keith-CY — APPROVED** [review]

**Comment by Keith-CY** [comment]
@FrederLu please have a review

**Comment by FrederLu** [comment]
https://godwoken-explorer-ui-git-fix-alert-default-type-nervosnet.vercel.app/token/40446
@qiweiii  You can still see the exception message on the above link. Please confirm.
image

**Comment by qiweiii** [comment]
> https://godwoken-explorer-ui-git-fix-alert-default-type-nervosnet.vercel.app/token/40446 @qiweiii You can still see the exception message on the above link. Please confirm. image image

Yes, this is expected, do you think we should remove it together with alert message?

**Comment by FrederLu** [comment]
The screenshot means that when the alter information (correct/error) disappears, the abnormal prompt of the screenshot will appear, and the abnormal prompt in the screenshot needs to be handled.

**Comment by qiweiii** [comment]
Fixed

**Review by FrederLu — APPROVED** [review]

**Pull request merged**
