### PR TITLE
fix: home page problems

### PR DESCRIPTION
**Pull request by qiweiii**
1. footer
image

2. special addr
image

Also fixed home page overflow

### CODE REVIEW

**Comment by qiweiii** [comment]
Also removed `global.css` and merged it into `global.scss`, not if `global.css` was left there deliberately, if need it I will recover the file.

**Comment by Kirl70** [comment]
The special address doesn't seem to be aligned yet

image

**Comment by qiweiii** [comment]
Updated https://godwoken-explorer-hniqoi2nm-nervosnet.vercel.app/, please check

**Review by Kirl70 — APPROVED** [review]

**Comment by Kirl70** [comment]
The homepage list of the mobile terminal I think only needs to list the latest 5 data. Users who want to view more data can go to the corresponding list page to view.

image

**Comment by qiweiii** [comment]
@Kirl70 We can change list item numbers and add status icon and maybe other home page new features in another PR, this PR is for bug fix

**Comment by Kirl70** [comment]
> @Kirl70我们可以在另一个 PR 中更改列表项编号并添加状态图标以及其他主页新功能，此 PR 用于修复错误



> @Kirl70 We can change list item numbers and add status icon and maybe other home page new features in another PR, this PR is for bug fix

got

**Review by FrederLu — APPROVED** [review]

**Pull request merged**
