### PR TITLE
feat: txs list filters

### PR DESCRIPTION
**Pull request by qiweiii**
Filter transactions list
- filtered by block number (from and to)
- filtered by method id/name
- filtered by from
- filtered by to
- filtered by age (from and to)

image

### CODE REVIEW

**Comment by FrederLu** [comment]
https://godwoken-explorer-oj8qu0u7l-magickbase.vercel.app/account/0xbfbe23681d99a158f632e64a31288946770c7a9e?tab=transactions&id=0xbfbe23681d99a158f632e64a31288946770c7a9e
image

The data of `Send` under Method cannot be filtered.
The hash of `polyjuice creator` under From/To cannot be filtered.

**Comment by qiweiii** [comment]
> https://godwoken-explorer-oj8qu0u7l-magickbase.vercel.app/account/0xbfbe23681d99a158f632e64a31288946770c7a9e?tab=transactions&id=0xbfbe23681d99a158f632e64a31288946770c7a9e image
> 
> The data of `Send` under Method cannot be filtered. The hash of `polyjuice creator` under From/To cannot be filtered.

@FrederLu 
- `Send` is not a method, it appears when the tx has no method
- I just tested filter by `hash of polyjuice creator`, seems backend doesn't support this kind of hash address in `from_eth_address` or `to_eth_address`:

image

**Comment by FrederLu** [comment]
> > https://godwoken-explorer-oj8qu0u7l-magickbase.vercel.app/account/0xbfbe23681d99a158f632e64a31288946770c7a9e?tab=transactions&id=0xbfbe23681d99a158f632e64a31288946770c7a9e image
> > The data of `Send` under Method cannot be filtered. The hash of `polyjuice creator` under From/To cannot be filtered.
> 
> @FrederLu
> 
> * `Send` is not a method, it appears when the tx has no method
> * I just tested filter by `hash of polyjuice creator`, seems backend doesn't support this kind of hash address in `from_eth_address` or `to_eth_address`:
> 
> image

@qiweiii 
To communicate with the backend, the second problem needs to be dealt with by the interface first. Later, I will link an issue first, and then the frontend will deal with it after the backend is processed.

**Comment by FrederLu** [comment]
Requires back-end processing first https://github.com/Magickbase/godwoken_explorer/issues/1229

**Review by Keith-CY — APPROVED** [review]

**Comment by Keith-CY** [comment]
Where is the design of `method name/id` filter from, I didn't find it in figma
image

**Comment by qiweiii** [comment]
@Keith-CY 
There is no figma design for method filter

**Comment by Naupio** [comment]
> > https://godwoken-explorer-oj8qu0u7l-magickbase.vercel.app/account/0xbfbe23681d99a158f632e64a31288946770c7a9e?tab=transactions&id=0xbfbe23681d99a158f632e64a31288946770c7a9e image
> > The data of `Send` under Method cannot be filtered. The hash of `polyjuice creator` under From/To cannot be filtered.
> 
> @FrederLu
> 
>     * `Send` is not a method, it appears when the tx has no method
> 
>     * I just tested filter by `hash of polyjuice creator`, seems backend doesn't support this kind of hash address in `from_eth_address` or `to_eth_address`:
> 
> 
> image

`polyjuice creator`  transaction havn't eth_hash data,
you can use `hash` in from_script_hash or to_script_hash

**Comment by FrederLu** [comment]
> > > https://godwoken-explorer-oj8qu0u7l-magickbase.vercel.app/account/0xbfbe23681d99a158f632e64a31288946770c7a9e?tab=transactions&id=0xbfbe23681d99a158f632e64a31288946770c7a9e image
> > > The data of `Send` under Method cannot be filtered. The hash of `polyjuice creator` under From/To cannot be filtered.
> > 
> > 
> > @FrederLu
> > ```
> > * `Send` is not a method, it appears when the tx has no method
> > 
> > * I just tested filter by `hash of polyjuice creator`, seems backend doesn't support this kind of hash address in `from_eth_address` or `to_eth_address`:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > image
> 
> `polyjuice creator` transaction havn't eth_hash data, you can use `hash` in from_script_hash or to_script_hash cc @FrederLu
@Keith-CY 
If `polyjuice creator` data on the page cannot be used for From/To filtering, does the front end need to do processing?

**Comment by qiweiii** [comment]
@FrederLu It means this can be done in frontend, I will fix this

**Comment by FrederLu** [comment]
@qiweiii 
After using `polyjuice creator` to filter data, the page displays abnormal data.
https://godwoken-explorer-ln5md2z6m-magickbase.vercel.app/zh-CN/account/0xcc0af0af911dd40853b8c8dfee90b32f8d1ecad6?search=0xcc0af0af911dd40853b8c8dfee90b32f8d1ecad6&address_to=0x829cc5785a4d8ac642ede32cb3cb5cb9dc389d5892f2fc2afc760691445be194&before=g3QAAAADZAAMYmxvY2tfbnVtYmVyYgAIYVFkAARoYXNodAAAAANkAApfX3N0cnVjdF9fZAAiRWxpeGlyLkdvZHdva2VuRXhwbG9yZXIuQ2hhaW4uSGFzaGQACmJ5dGVfY291bnRhIGQABWJ5dGVzbQAAACDTRK3PmMqsShDQ0lhHevSwIyY7i9rpiAekfx1RXhfS_2QABWluZGV4YQA%3D
image

**Comment by qiweiii** [comment]
@FrederLu based on data from API, this abnormal entry has a `polyjuice.native_transfer_address_hash`, so the displayed `to address` is the `native_transfer_address_hash`, but it also has the correct `to_account.script_hash`
image

**Review by JeffreyMa597 — APPROVED** [review]

**Review by FrederLu — APPROVED** [review]

**Pull request merged**
