### PR TITLE
Refine account page

### PR DESCRIPTION
**Pull request by Keith-CY**
User account: https://godwoken-explorer-ui-git-refine-account-page-nervosnet.vercel.app/account/0x40dfb7df991c9aa6138a60f0cac6ed1d02b834b8
contract account: https://godwoken-explorer-ui-git-refine-account-page-nervosnet.vercel.app/account/0xe05d380839f32bc12fb690aa6fe26b00bd982613
polyjuice creator account: https://godwoken-explorer-ui-git-refine-account-page-nervosnet.vercel.app/account/0x829cc5785a4d8ac642ede32cb3cb5cb9dc389d5892f2fc2afc760691445be194
sudt account: https://godwoken-explorer-ui-git-refine-account-page-nervosnet.vercel.app/account/0x3e1301e759261b676ce68d0d97936cd431a4af2a34072aa94e44655909765eb4
meta contract account: https://godwoken-explorer-ui-git-refine-account-page-nervosnet.vercel.app/account/0x946d08cc356c4fe13bc49929f1f709611fe0a2aaa336efb579dad4ca197d1551?search=0x946d08cc356c4fe13bc49929f1f709611fe0a2aaa336efb579dad4ca197d1551

### CODE REVIEW

**Review by qiweiii — APPROVED** [review]

**Comment by FrederLu** [comment]
image
image

@Keith-CY 
There is no icon before the value column value in the UI draft on July 22, and now it needs to be displayed?

**Comment by Keith-CY** [comment]
> image
> 
> image
> 
> @Keith-CY There is no icon before the value column value in the UI draft on July 22, and now it needs to be displayed?

It's from a current feature in product environment and will be updated in task https://github.com/Magickbase/godwoken_explorer/issues/811

**Comment by FrederLu** [comment]
image
image
image

@qiweiii 
There are 4 problems:
1. The interval between the download edge and the user account information is too small;
2. The spacing is too large;
3. The scroll bar and the selected blue subscript overlap;
4. Lack of prompt information;

**Comment by Keith-CY** [comment]
> image
> 
> image
> 
> image
> 
> @Keith-CY There are 4 problems:
> 
> 1. The interval between the download edge and the user account information is too small;
> 2. The spacing is too large;
> 3. The scroll bar and the selected blue subscript overlap;
> 4. Lack of prompt information;

For the 2. point, the gap is enlarged because `Last Finalized Block Number` in https://godwoken-explorer-ui-git-refine-account-page-nervosnet.vercel.app/account/0x946d08cc356c4fe13bc49929f1f709611fe0a2aaa336efb579dad4ca197d1551?search=0x946d08cc356c4fe13bc49929f1f709611fe0a2aaa336efb579dad4ca197d1551 requires, this type of account is lost in design draft

**Comment by Keith-CY** [comment]
> image
> 
> image
> 
> image
> 
> @Keith-CY There are 4 problems:
> 
> 1. The interval between the download edge and the user account information is too small;
> 2. The spacing is too large;
> 3. The scroll bar and the selected blue subscript overlap;
> 4. Lack of prompt information;

Fixed by https://github.com/Magickbase/godwoken-explorer-ui/pull/361/commits/713918b44d2ab6c04ea21d82508b01fb7d373406

**Comment by FrederLu** [comment]
image
There is indeed a down arrow in the Call Static option in the contract.

**Comment by FrederLu** [comment]
image

image

1、The hash value lacks suspension;
2、L2 script duplicate name;

**Comment by FrederLu** [comment]
https://godwoken-explorer-6atjs72wr-nervosnet.vercel.app/account/0x946d08cc356c4fe13bc49929f1f709611fe0a2aaa336efb579dad4ca197d1551?search=0x946d08cc356c4fe13bc49929f1f709611fe0a2aaa336efb579dad4ca197d1551

image

The above link has an abnormal situation where multiple floating information can be displayed together on the mobile terminal. Normally, only one floating information will appear, and the second floating information will be hidden before it appears.

**Pull request merged**
