### PR TITLE
feat: add some filters

### PR DESCRIPTION
**Pull request by Keith-CY**
1. add block from/to filters in tx list of an account
2. add address from/to filters in transfer list of a tx

Ref: https://github.com/Magickbase/godwoken_explorer/issues/556

---

## Filter block from/to in tx list of an account

https://user-images.githubusercontent.com/7271329/174867302-1b9fba35-6770-462e-b32c-29c2a6d92659.mov

## Filter address from/to in transfer list of a tx

https://user-images.githubusercontent.com/7271329/174867383-cbcda691-4278-4588-ae95-2e75ac5cf873.mov

### CODE REVIEW

**Review by qiweiii — APPROVED** [review]

**Review by yanguoyu — APPROVED** [review]

**Comment by FrederLu** [comment]
image
image
image
1、When filtering from/to in the Transaction Info list, when the wrong value is used (one digit is missing compared to the correct value or an abnormal value A// is entered), and the Chinese format is not filtered (你好or Chinese punctuation), the page will display abnormal..

image
2、2 similar requests were found when using from/to filtering.

image
3、user account page from/to is filtered Chinese characters, punctuation and letters are filtered, but E/e letters are not filtered; when you enter E/e letters and click to filter button, the prompt information is Chinese (the page is in English ).

**Comment by Keith-CY** [comment]
> 1、When filtering from/to in the Transaction Info list, when the wrong value is used (one digit is missing compared to the correct value or an abnormal value A// is entered), and the Chinese format is not filtered (你好or Chinese punctuation), the page will display abnormal..

Is fixed in [39897f5](https://github.com/Magickbase/godwoken-explorer-ui/pull/235/commits/39897f57f2814b573de681b2172e15ab6089f6b8) by handling error responses from api

> 2、2 similar requests were found when using from/to filtering.

It's a mechanism of client cache, api requests sent by page will be proxied by `service worker` and will be cached, cache value will be returned in the next same request.

The first record is `page -> service worker`, the second record is `service worker -> backend`

> 3、user account page from/to is filtered Chinese characters, punctuation and letters are filtered, but E/e letters are not filtered; when you enter E/e letters and click to filter button, the prompt information is Chinese (the page is in English ).

This popup is for browser-builtin validation, so the language is based on the browser and cannot be changed by code. We can disable the native validation but not necessary.

**Comment by FrederLu** [comment]
> Points 1 and 2 are ok. Question 3, when the browser language is English, it can only display Chinese? Furthermore, only numbers should be entered here, but E/e letters can be entered.

**Comment by Keith-CY** [comment]
> Points 1 and 2 are ok. Question 3, when the browser language is English, it can only display Chinese?（"This popup is for browser-builtin validation, so the language is based on the browser and cannot be changed by code."） Furthermore, only numbers should be entered here, but E/e letters can be entered.

The prompt is in language which browser is using
image

`e` is special because it represents scientific notation, `1e2` means `100`

**Comment by Keith-CY** [comment]
> > `e` is special because it represents scientific notation, `1e2` means `100`
> > image
> 
> e is not processed when used as scientific notation.

Fixed in [4fd78c7](https://github.com/Magickbase/godwoken-explorer-ui/pull/235/commits/4fd78c77ad7d10754f23570f28b0885d2de8f3be), `1e3` in query will be transformed into `1000`

**Comment by Keith-CY** [comment]
> address from/to filters in transfer list of a tx is only available on PC, not on mobile phones; filtering in an accounts is available on both.

Filter in `transfer` column is added by [0c80dd6](https://github.com/Magickbase/godwoken-explorer-ui/pull/235/commits/0c80dd6ae629cbce786848072473bffdaeda6e9a)

**Comment by Keith-CY** [comment]
> `2. add address from/to filters in transfer list of a tx`
> 
> Combined filtering is not supported. After the filter takes effect, the previous filter (From or To) is automatically cleared.
> 
>  2022-06-24.00.17.05.mov

Combination of filters is added by [a404a65](https://github.com/Magickbase/godwoken-explorer-ui/pull/235/commits/a404a65b08044a3ab45b5e0f899692144008bd8c)

**Comment by Cedar67** [comment]
> > `2. add address from/to filters in transfer list of a tx`
> > Combined filtering is not supported. After the filter takes effect, the previous filter (From or To) is automatically cleared.
> > 2022-06-24.00.17.05.mov
> 
> Combination of filters is added by [a404a65](https://github.com/Magickbase/godwoken-explorer-ui/pull/235/commits/a404a65b08044a3ab45b5e0f899692144008bd8c)
> 
> https://godwoken-explorer-ui-git-support-filtering-nervosnet.vercel.app/tx/0xd184e6e20ce27d6abf073890c01c9ffddb5c68c2da1b384998e439cb8f954e2b

Verified.

**Review by Cedar67 — APPROVED** [review]

**Comment by FrederLu** [comment]
> > address from/to filters in transfer list of a tx is only available on PC, not on mobile phones; filtering in an accounts is available on both.
> 
> Filter in `transfer` column is added by [0c80dd6](https://github.com/Magickbase/godwoken-explorer-ui/pull/235/commits/0c80dd6ae629cbce786848072473bffdaeda6e9a)
> 
> https://godwoken-explorer-ui-git-support-filtering-nervosnet.vercel.app/tx/0xe3e5bc75cf2151abc70db9ae10c2d76ac5846e7a0eca1d39f9d55632e83a2077

Verified.

**Review by FrederLu — APPROVED** [review]

**Pull request merged**
