### PR TITLE
feat: add method field in tx list

### PR DESCRIPTION
**Pull request by Keith-CY**
All tx list: https://godwoken-explorer-ui-git-display-method-nervosnet.vercel.app/txs
Tx List of a block: https://godwoken-explorer-ui-git-display-method-nervosnet.vercel.app/block/0x62034ba12a9c744b812c12e1c54083bd1b082f0feb50dbe9b863063478c0362c
Tx List of an account: https://godwoken-explorer-ui-git-display-method-nervosnet.vercel.app/account/0x1cb9c569d3f9682a685ef32371b6cfea2a738b51
Ref: https://github.com/Magickbase/godwoken_explorer/issues/762

### CODE REVIEW

**Review by qiweiii — APPROVED** [review]

**Comment by FrederLu** [comment]
image

@Keith-CY 
https://godwoken-explorer-khpf27vy6-nervosnet.vercel.app/zh-CN
The page data is displayed abnormally, and the interface reports 502.

**Comment by Keith-CY** [comment]
> image
> 
> @Keith-CY https://godwoken-explorer-khpf27vy6-nervosnet.vercel.app/zh-CN The page data is displayed abnormally, and the interface reports 502.

Please check if all requests to backend are down(I’m not at the table for now). If yes, we may need help from backend engineers.

**Comment by FrederLu** [comment]
image
image
image

There are exceptions when looking at the request page.

**Comment by FrederLu** [comment]
image

The method display of 2 pieces of data on [the page](https://godwoken-explorer-khpf27vy6-nervosnet.vercel.app/account/0x39784ddab654e8469498cb24ead628e6df644ec9?page_size=50&after=g3QAAAADZAAMYmxvY2tfbnVtYmVyYgAEInBkAARoYXNodAAAAANkAApfX3N0cnVjdF9fZAAiRWxpeGlyLkdvZHdva2VuRXhwbG9yZXIuQ2hhaW4uSGFzaGQACmJ5dGVfY291bnRhIGQABWJ5dGVzbQAAACBplPC_x5VUTGHFJqQCvuI-DcF2gUqoJV8DeyTKVXyAzmQABWluZGV4YQA%3D) is abnormal.

**Comment by Keith-CY** [comment]
> image
> 
> The method display of 2 pieces of data on [the page](https://godwoken-explorer-khpf27vy6-nervosnet.vercel.app/account/0x39784ddab654e8469498cb24ead628e6df644ec9?page_size=50&after=g3QAAAADZAAMYmxvY2tfbnVtYmVyYgAEInBkAARoYXNodAAAAANkAApfX3N0cnVjdF9fZAAiRWxpeGlyLkdvZHdva2VuRXhwbG9yZXIuQ2hhaW4uSGFzaGQACmJ5dGVfY291bnRhIGQABWJ5dGVzbQAAACBplPC_x5VUTGHFJqQCvuI-DcF2gUqoJV8DeyTKVXyAzmQABWluZGV4YQA%3D) is abnormal.

Please append url or user address so we can locate the exception

**Review by FrederLu — APPROVED** [review]

**Pull request merged**
