### PR TITLE
new ui for home page

### PR DESCRIPTION
**Pull request by qiweiii**
related parts:
- [x] home stats
- [x] Search
- [x] Search empty
- [x] 404
- [x] home block list
- [x] home tx list

### CODE REVIEW

**Comment by Keith-CY** [comment]
Seems not ready for review
image

**Comment by qiweiii** [comment]
@Keith-CY works on my machine and phone, maybe cache problem?

image

**Comment by Kirl70** [comment]
image
我这边用无痕模式以及不同浏览器看也是一样的问题 @qiweiii

**Comment by qiweiii** [comment]
@Kirl70 @FrederLu  @Keith-CY 

Please view deployment at: https://godwoken-explorer-o4ji83663-nervosnet.vercel.app/

seems vercel did not update content

**Comment by Kirl70** [comment]
PC：
image
1、导航栏的交互改为鼠标hover即出现下拉框，不需要点击了才出现 2、输入文案与icon间距是16px
3、视频的尺寸改为MP4的原始尺寸，现在似乎过大。视频部分的高度改为444px。 4、悬浮框背景色为#000000 ，80%透明度。
5、列表数据鼠标hover需出现背景色，色值参考figma。

image
将这两个数据的padding 24px 改为60px，现在看上去有点拥挤。

image
底部间距高度改为88px。

**Comment by Kirl70** [comment]
mobile：
image
中文状态下似乎还是有问题

image

能不能把浏览器自带的播放控件给隐藏掉

**Comment by FrederLu** [comment]
image
Abnormal display when the page is in Chinese（
When using the English page, the page is normal, and it is normal after adjusting to Chinese, but it is abnormal when the page is refreshed in Chinese.）.

**Comment by Kirl70** [comment]
@FrederLu 查看画板背景颜色需要点击画板名称才会显示，如图所示

image

**Comment by FrederLu** [comment]
image
image
image
image

The search is empty and the 404 should be separate (2 pages on the ui draft), now it's mixed up.

**Comment by qiweiii** [comment]
@FrederLu search empty and 404 page are not mixed up, and I did not change code related to browser tab title, I think the current display is correct because both empty search result and wrong url are indicated by 404 status code from server:

image

which means resource not found on server, so I think they are fine.

And for design, the text at top left corner, I believe they are not part of the website, they are just simple description for designer/developer to see what feature it is.

**Comment by qiweiii** [comment]
@Kirl70 How to fix this on UX? 

image

may be shorten the address even more when in Chinese language, just an idea..

@Kirl70 @FrederLu, All other problems are fine to fix, will be done soon

**Comment by Kirl70** [comment]
> @Kirl70 How to fix this on UX?
> 
> image
> 
> may be shorten the address even more when in Chinese language, just an idea..
> 
> @Kirl70 @FrederLu, All other problems are fine to fix, will be done soon

image
在我的iPhone上看，如果默认打开是中文的话是会出现文字外溢问题，不过当我切换英文再切回中文，外溢问题就不出现了。先看一下能不能解决，如果不能就在中文的情况下缩短地址，比如前后各保留4位数。 @qiweiii

**Comment by Kirl70** [comment]
https://user-images.githubusercontent.com/106060898/177480981-e5d0d44e-975e-4eba-89cb-e164fe471fb8.mp4

头图数据需要做成递增效果，递增时间控制在2秒。

**Comment by qiweiii** [comment]
@FrederLu @Kirl70 https://godwoken-explorer-ui-git-ui-home-nervosnet.vercel.app/zh-CN

check out the new preview

**Comment by Kirl70** [comment]
PC：

image

黑色遮罩透明度值与设计稿不符。

image

弹出框阴影大小色值与设计稿不符。


mobile：

image

间距细节还需调整一下，统计数据看起来过于拥挤。

image

右边文字需水平居中左边图标。


image

动图在不影响左边数据时尽可能放大，可以贴最右边，不需要对齐。PS.在手机上看还是会出现浏览器自带的播放控件，能否隐藏掉？ @qiweiii

**Comment by FrederLu** [comment]
> @FrederLu search empty and 404 page are not mixed up, and I did not change code related to browser tab title, I think the current display is correct because both empty search result and wrong url are indicated by 404 status code from server:
> 
> image
> 
> which means resource not found on server, so I think they are fine.
> 
> And for design, the text at top left corner, I believe they are not part of the website, they are just simple description for designer/developer to see what feature it is.

@qiweiii I know what you mean, the request status is not found is 404, but here I see that the UI draft is separated, @Kirl70  what should I do here?

**Comment by Kirl70** [comment]
> > @FrederLu搜索空和404页面没有混淆，我没有更改浏览器标签标题相关的代码，我认为当前显示是正确的，因为空搜索结果和错误的url都是由服务器的404状态码指示的：
> > 图片
> > 这意味着在服务器上找不到资源，所以我认为它们很好。
> > 而对于设计，左上角的文字，我相信它们不是网站的一部分，它们只是设计师/开发人员的简单描述，以了解它是什么功能。
> 
> @qiweiii我知道你的意思，request status is not found 是 404，但是这里我看到 UI 草稿是分开的，@Kirl70 我应该在这里做什么？是根据UI单独处理，还是根据当前显示。

设计稿上是让开发人员知道会有存在一个404的图标/页面，具体出现的情况根据页面的结果返回而定。不一定是出现在搜索结果后。 或者我们可不可以去掉这个404的字样，减少误解。 @qiweiii 

image

**Comment by FrederLu** [comment]
image
@Kirl70  @qiweiii 

1.After the delete button in the input box is displayed, the input information is manually deleted instead of the delete button. Is this button displayed or hidden?  I don't know if I can refer to the [url](https://pudge.explorer.nervos.org/) for some interactive experience.
2. The delete button is displayed only when 2 characters (number and space) are input, and not when 1 character is input.
3. The delete button is not displayed when entering Chinese and English.

**Comment by Kirl70** [comment]
> image
> 
> @Kirl70 @qiweiii
> 1.After the delete button in the input box is displayed, the input information is manually deleted instead of the delete button. Is this button displayed or hidden? I don't know if I can refer to the [url](https://pudge.explorer.nervos.org/) for some interactive experience. 2. The delete button is displayed only when 2 characters (number and space) are input, and not when 1 character is input. 3. The delete button is not displayed when entering Chinese and English.



> 

1.删除输入内容后删除按钮也应同时消失。
后面的问题应该都是bug，建议可以参照[https://pudge.explorer.nervos.org/](url)的搜索逻辑来做。 @qiweiii

**Comment by Kirl70** [comment]
> image
> 
> @Kirl70 在UI稿中每个页面上的搜索框和CKB上的位置和逻辑不同。输入相应信息搜索到结果并跳转到对应页面，此时结果页的搜索框中保留了搜索的信息(看CKB上好像是为空不记录搜索信息)，不清楚这块交互是否参考CKB，如果不参考这时输入框中有带过来的信息却没有显示删除按钮。

只需要参考搜索的逻辑即可，比如删除按钮在什么时候显示/消失，其它的位置和样式都不变。在进行搜索操作后，搜索信息不保留在搜索框，即回到未输入状态。另外我觉得可以限制搜索框可输入字符最多不超过100个，这样可以避免因为内容过长导致结果页显示问题。

image

**Comment by FrederLu** [comment]
Block List UI：
image
image

image
image

@Kirl70  Does the following list need to be consistent with the UI draft?
Spacing problem：1、7、8、11
Letter case problem：3
The chamfer arc is not uniform：2
Page number style：4、10
Style, font color：5、6
Tips：9

**Comment by Kirl70** [comment]
> Block List UI： image image
> 
> image
> 
> image
> 
> @Kirl70 Does the following list need to be consistent with the UI draft? Spacing problem：1、7、8、11 Letter case problem：3 The chamfer arc is not uniform：2 Page number style：4、10 Style, font color：5、6 Tips：9

新的UI样式应该还没开发到列表页，这样问题是目前线上的样式。

**Comment by FrederLu** [comment]
> > Block List UI： image image
> > image
> > image
> > @Kirl70 Does the following list need to be consistent with the UI draft? Spacing problem：1、7、8、11 Letter case problem：3 The chamfer arc is not uniform：2 Page number style：4、10 Style, font color：5、6 Tips：9
> 
> 新的UI样式应该还没开发到列表页，这些问题是目前线上的样式。

嗯，和开发确认了是首页中的block、tx list。

**Comment by qiweiii** [comment]
@Kirl70 tooltip style is already following design, maybe your device has some settings turned on, there are settings like true tone and other color stuff effects, so they may make web ui looks a bit different to your design.
image

@FrederLu The 11111111111111111111 problem is weired, returned status code is 500, maybe this search value caused an error in backend, may need backend colleague to help.

Other issues should be fixed.
https://godwoken-explorer-gbomcvnxg-nervosnet.vercel.app/

**Comment by FrederLu** [comment]
image
> @FrederLu The 11111111111111111111 problem is weired, returned status code is 500, maybe this search value caused an error in backend, may need backend colleague to help.
> 
> Other issues should be fixed. https://godwoken-explorer-gbomcvnxg-nervosnet.vercel.app/

@Keith-CY The search interface reports 500 at the input 11111111111111111111 interface. Which small partner should I take a look at?

**Comment by Kirl70** [comment]
mobile：
image

间距不对

image

图标大小不对。输入的文字色值应该为#333，搜索框点击后要有描边样式（PC同理）。

**Comment by qiweiii** [comment]
@Kirl70 You just said yesterday home page don't need border, so I have done that...do you confirm need to add focus border in home page.

**Comment by Kirl70** [comment]
> @Kirl70 You just said yesterday home page don't need border, so I have done that...do you confirm need to add focus border in home page.

昨天说的是默认状态主页是没有描边样式，其它页面要有（灰色）。
image

image

——————————————————————————————

但是点击/输入状态是要有高亮的边框，主页，其它页面都要有（主色）。

image

**Comment by FrederLu** [comment]
> Other issues should be fixed. https://godwoken-explorer-gbomcvnxg-nervosnet.vercel.app/

@qiweiii 
Verified question：
1、The search box delete button is displayed
2、The page 404
3、The android mobile phone data exceeds the layout problem
4、Chinese page animation layout is abnormal

Still have questions：
1、The android phone is missing the right half of the animation

**Comment by FrederLu** [comment]
> Still have questions： 1、The android phone is missing the right half of the animation image

@Keith-CY @qiweiii 
When the [url](https://godwoken-explorer-caqppev6x-nervosnet.vercel.app) is opened in WeChat, when the page is in Chinese, the dynamic image is abnormally displayed and blank. After switching to English, it can be displayed normally. After switching to Chinese, the page is refreshed and blank again. Is there any good solution for this?

**Comment by Keith-CY** [comment]
> > Still have questions： 1、The android phone is missing the right half of the animation image
> 
> @Keith-CY @qiweiii When the [url](https://godwoken-explorer-caqppev6x-nervosnet.vercel.app) is opened in WeChat, when the page is in Chinese, the dynamic image is abnormally displayed and blank. After switching to English, it can be displayed normally. After switching to Chinese, the page is refreshed and blank again. Is there any good solution for this?

It could be fixed if layout is correct when the language is set to English. It should be an error in the banner since it disappears when I visit the English page in WeChat directly https://godwoken-explorer-ui-git-ui-home-nervosnet.vercel.app/en-US

**Comment by FrederLu** [comment]
Now, except that the animation of the Chinese page is not displayed when the Android phone is opened in WeChat, other problems have been verified.

**Review by Keith-CY — APPROVED** [review]

**Review by FrederLu — APPROVED** [review]

**Review by Kirl70 — APPROVED** [review]

**Pull request merged**
