### PR TITLE
fix: fix style of empty list

### PR DESCRIPTION
**Pull request by Keith-CY**
1. asset list of an account: https://godwoken-explorer-ui-git-update-style-of-empty-list-nervosnet.vercel.app/account/0xde2022a8ab68ae86b0cd3ba5efa10aab859d0293?tab=assets
2. bridged transfer list: https://godwoken-explorer-ui-git-update-style-of-empty-list-nervosnet.vercel.app/account/0xde2022a8ab68ae86b0cd3ba5efa10aab859d0293?tab=bridged
3. contract events: https://godwoken-explorer-ui-git-update-style-of-empty-list-nervosnet.vercel.app/account/0x4e4fa411c6ed5a02889be7b88b9397e93f0e97d3?tab=events
4. erc20 transfer list: 
    - https://godwoken-explorer-ui-git-update-style-of-empty-list-nervosnet.vercel.app/tx/0x253f3c916418fe4da3746a2e9354081e7f82e6e278382465433747ea5172debb
    - https://godwoken-explorer-ui-git-update-style-of-empty-list-nervosnet.vercel.app/account/0x47152488115bb6a01ebaa0d5c7f8ad718b01d0ae?tab=erc20
5. token holder list
6. tx list: https://godwoken-explorer-ui-git-update-style-of-empty-list-nervosnet.vercel.app/account/0x47152488115bb6a01ebaa0d5c7f8ad718b01d0ae?id=0x47152488115bb6a01ebaa0d5c7f8ad718b01d0ae&block_from=999999
7. block list
8. tx logs list https://godwoken-explorer-ui-git-update-style-of-empty-list-nervosnet.vercel.app/tx/0xcb14bd10bb8ac86771b60756c6808c8bea9d7cee1d65c352fc240aea052dd787?tab=logs
9. token list: https://godwoken-explorer-ui-git-update-style-of-empty-list-nervosnet.vercel.app/tokens/native?type=native&name=testtest

10. add a tooltip in the bridged token list with text `view mapped native token` to tell users that clicking a bridged token navigates to its corresponding native token detail page

### CODE REVIEW

**Review by qiweiii — APPROVED** [review]

**Comment by FrederLu** [comment]
contract events: https://godwoken-explorer-ui-git-update-style-of-empty-list-nervosnet.vercel.app/account/0x4e4fa411c6ed5a02889be7b88b9397e93f0e97d3?tab=events
image

No Records can't be clicked, the text color uses #333333.

**Comment by FrederLu** [comment]
image

@Kirl70
Is there a difference between the icons used on empty state pages related to transaction tabs and those used on non-transaction-related empty state pages?

**Comment by Kirl70** [comment]
> image
> 
> @Kirl70 Is there a difference between the icons used on empty state pages related to transaction tabs and those used on non-transaction-related empty state pages?

Related to searching or filtering are search picture, the rest are picture for empty folders.

**Comment by Keith-CY** [comment]
There're three lists supporting filter
1. ERC20 Transfer of a transaction
  - empty list: https://godwoken-explorer-ui-git-update-style-of-empty-list-nervosnet.vercel.app/tx/0x513d9607d27c6ac5ca58aa2ee43cbf5a1d391f056e04130b794c0faad8c7a15d
  - empty filtered list: https://godwoken-explorer-ui-git-update-style-of-empty-list-nervosnet.vercel.app/tx/0x513d9607d27c6ac5ca58aa2ee43cbf5a1d391f056e04130b794c0faad8c7a15d?address_from=1
2. Transaction list of (a block, an account, all transactions)
  - empty list: https://godwoken-explorer-ui-git-update-style-of-empty-list-nervosnet.vercel.app/block/0x460a83f038f4b861af50b055a6c6bc9ef2afffc09e4ac5ae732b2a37f6967758
  - empty filtered list: https://godwoken-explorer-ui-git-update-style-of-empty-list-nervosnet.vercel.app/block/0x460a83f038f4b861af50b055a6c6bc9ef2afffc09e4ac5ae732b2a37f6967758?id=0x460a83f038f4b861af50b055a6c6bc9ef2afffc09e4ac5ae732b2a37f6967758&block_from=1
3. Token List
  - empty list: https://godwoken-explorer-ui-git-update-style-of-empty-list-nervosnet.vercel.app/tokens/bridge
  - empty filtered list: https://godwoken-explorer-ui-git-update-style-of-empty-list-nervosnet.vercel.app/tokens/bridge?type=bridge&name=1

**Comment by Keith-CY** [comment]
> 1、No Records can't be clicked, the text color uses #333333.
> 2、The events tab without data on the [UI draft](https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=4067%3A20181) does not need to display information such as search.

Fixed too

**Comment by Keith-CY** [comment]
> 3、When there is no content, the page title sorting/filtering icons and empty state prompt information are also inconsistent with the [UI draft](https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=4078%3A20510).

Are filtered removed on purpose in this case @Kirl70

**Comment by Kirl70** [comment]
> > 3、When there is no content, the page title sorting/filtering icons and empty state prompt information are also inconsistent with the [UI draft](https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=4078%3A20510).
> 
> Are filter/sort icons removed on purpose in this case @Kirl70

No need to show filter/sort icons when there is no content.

**Comment by Keith-CY** [comment]
> > > 3、When there is no content, the page title sorting/filtering icons and empty state prompt information are also inconsistent with the [UI draft](https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=4078%3A20510).
> > 
> > 
> > Are filter/sort icons removed on purpose in this case @Kirl70
> 
> No need to show filter/sort icons when there is no content.

Got it and will be updated today

**Comment by Keith-CY** [comment]
Filter/Sort icons are hidden if total count is 0 by [a58dd96](https://github.com/Magickbase/godwoken-explorer-ui/pull/417/commits/a58dd965632c3b900575c2050fba5e3138b844fc) @FrederLu

**Comment by FrederLu** [comment]
Add a tooltip to the bridge token list with a text view mapping native token that needs to be validated in the pro environment due to lack of data in the test environment.

**Review by FrederLu — APPROVED** [review]

**Pull request merged**
