### PR TITLE
Feat: change the pagination to cursor and add sorter --- NFT collections

### PR DESCRIPTION
**Pull request by JeffreyMa597**
What problem does this PR solve?
------
This PR is for the page of `NFT-collections`.

Ref: https://github.com/Magickbase/godwoken_explorer/issues/556

Check List
------
1、sorted by total supply/circulating supply
2、sorted by holders
3、sorted by name
4、filtered by name (fuzzy)

### Test
e2e Test
### Task
none

### CODE REVIEW

**Comment by JeffreyMa597** [comment]
@Naupio Please also pay attention to my comment under this issue. Cause we still missing a sorter in the API of this page. If I make a mistake. Please let me know. Thanks a lot.

image

**Comment by JeffreyMa597** [comment]
@Naupio Please post your PRs, if you finish the update. So, I can track it. Thanks a lot.

**Comment by JeffreyMa597** [comment]
imag@Naupio

@Naupio I wondered whether it is expected when I sorted the `minted_count` in `ASC`.

**Review by FrederLu — APPROVED** [review]

**Review by Keith-CY — APPROVED** [review]

**Comment by FrederLu** [comment]
@JeffreyMa597 
The E2E test shows that there is a problem, you need to look at it.
image

**Pull request merged**
